In [2]:
import molsysmt as msm

/home/diego/Myopt/miniconda3/envs/MolSysMT@uibcdf_3.12/lib/python3.12/site-packages/nglview/__init__.py:12: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [3]:
import pandas as pd
import numpy as np

In [4]:
molsys_Hk2 = msm.convert(msm.systems['Hexokinase 2']['2nzt.bcif.gz'])

In [5]:
molsys_BB = msm.convert(msm.systems['Barnase-Barstar']['1brs.bcif.gz'])

In [6]:
molsys_Hk2.topology.atoms

       atom_id atom_name atom_type  group_index  component_index  chain_index
0            1         N         N            0                0            0
1            2        CA         C            0                0            0
2            3         C         C            0                0            0
3            4         O         O            0                0            0
4            5        CB         C            0                0            0
...        ...       ...       ...          ...              ...          ...
13541    13542         O         O         1866              141           39
13542    13543         O         O         1867              142           39
13543    13544         O         O         1868              143           39
13544    13545         O         O         1869              144           39
13545    13546         O         O         1870              145           39

[13546 rows x 6 columns]

In [8]:
item=molsys_Hk2.topology

In [9]:
indices=[4,5,6]

In [22]:
subset = item.atoms.loc[item.atoms['group_index'].isin(indices)]

In [25]:
grouped = subset.groupby('group_index')['atom_name'].groups

In [26]:
grouped

{4: [33, 34, 35, 36, 37, 38, 39, 40, 41], 5: [42, 43, 44, 45, 46, 47, 48], 6: [49, 50, 51, 52, 53, 54, 55, 56]}

In [14]:
subset

    atom_id atom_name atom_type  group_index  component_index  chain_index
33       34         N         N            4                0            0
34       35        CA         C            4                0            0
35       36         C         C            4                0            0
36       37         O         O            4                0            0
37       38        CB         C            4                0            0
38       39        CG         C            4                0            0
39       40        CD         C            4                0            0
40       41        CE         C            4                0            0
41       42        NZ         N            4                0            0
42       43         N         N            5                0            0
43       44        CA         C            5                0            0
44       45         C         C            5                0            0
45       46         O         O            5                0            0
46       47        CB         C            5                0            0
47       48       CG1         C            5                0            0
48       49       CG2         C            5                0            0
49       50         N         N            6                0            0
50       51        CA         C            6                0            0
51       52         C         C            6                0            0
52       53         O         O            6                0            0
53       54        CB         C            6                0            0
54       55        CG         C            6                0            0
55       56       OD1         O            6                0            0
56       57       OD2         O            6                0            0

In [27]:
output = [subset['atom_id'].iat(grouped.get(ii, [])).tolist() for ii in indices]

TypeError: '_iAtIndexer' object is not callable

In [ ]:
output

In [1]:
selected_groups = item.atoms.loc[item.atoms['group_index'].isin(indices)]
grouped = selected_groups.groupby('group_index')['atom_id'].groups
output = [selected_groups['atom_id'].take(grouped.get(ii, [])).tolist() for ii in indices]

NameError: name 'item' is not defined

In [7]:
all_Hk2 = msm.form.molsysmt_Topology.get_atom_id_from_group(molsys_Hk2.topology, skip_digestion=True)
all_BB = msm.form.molsysmt_Topology.get_atom_id_from_group(molsys_BB.topology, skip_digestion=True)
list_Hk2 = msm.form.molsysmt_Topology.get_atom_id_from_group(molsys_Hk2.topology, [4,5,6], skip_digestion=True)
list_BB = msm.form.molsysmt_Topology.get_atom_id_from_group(molsys_BB.topology, [10,11,12,13], skip_digestion=True)

IndexError: indices are out-of-bounds

In [ ]:
len(all_Hk2)

In [ ]:
len(all_BB)

In [ ]:
all_Hk2[344:347]

In [ ]:
all_Hk2[1750:1755]

In [ ]:
all_Hk2[0]

In [ ]:
all_Hk2[-1]

In [ ]:
all_BB[385:388]

In [ ]:
all_BB[586:592]

In [ ]:
all_BB[0]

In [ ]:
all_BB[-1]

In [ ]:
list_Hk2

In [ ]:
list_BB