In [1]:
import molsysmt as msm
import pandas as pd
import numpy as np

/conda/miniconda3/envs/MolSysMT@uibcdf_3.12/lib/python3.12/site-packages/nglview/__init__.py:12: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [2]:
molsys = msm.convert('pdb_id:181l', to_form='molsysmt.MolSys')

In [3]:
molsys.topology.molecules

     molecule_id             molecule_name molecule_type  entity_index
0              0               T4 LYSOZYME       protein             0
1              1              CHLORIDE ION       unknown             1
2              2              CHLORIDE ION       unknown             1
3              3  2-HYDROXYETHYL DISULFIDE       unknown             2
4              4                   BENZENE       unknown             3
..           ...                       ...           ...           ...
136          136                     water         water             4
137          137                     water         water             4
138          138                     water         water             4
139          139                     water         water             4
140          140                     water         water             4

[141 rows x 4 columns]

In [4]:
molsys = msm.basic.remove(molsys, selection='group_type in ["ion", "water"]')

In [5]:
molsys = msm.basic.remove(molsys, selection='atom_type=="H"')

In [6]:
molsys.topology.chains

  chain_id chain_name chain_type
0        A          A    protein
1        D          A    unknown
2        E          A    unknown

In [7]:
molsys = msm.build.add_missing_terminal_cappings(molsys, N_terminal='ACE', C_terminal='NME')

In [12]:
aa=list(molsys.topology.chains())

In [14]:
chain = aa[0]

'A'

In [ ]:
molsys.topology.atoms

In [ ]:
molsys = msm.build.add_missing_hydrogens(molsys, pH=7.4)
_ = msm.convert(molsys, to_form='t4_lysozyme_L99A.h5msm')
shutil.move('t4_lysozyme_L99A.h5msm', Path(data_dir, 'h5msm/t4_lysozyme_L99A.h5msm'))