In [1]:
import molsysmt as msm
import pandas as pd
import numpy as np

/home/diego/Myopt/miniconda3/envs/MolSysMT@uibcdf_3.12/lib/python3.12/site-packages/nglview/__init__.py:12: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

Hay un problema con data/h5msm/t4_lysozyme_L99A

In [2]:
molsys = msm.convert('pdb_id:181l', to_form='molsysmt.MolSys')

In [3]:
molsys.topology.chains

  chain_id chain_name chain_type
0        A          A    protein
1        B          A    unknown
2        C          A    unknown
3        D          A    unknown
4        E          A    unknown
5        F          A      water

In [4]:
molsys = msm.basic.remove(molsys, selection='group_type in ["ion", "water"]')
molsys = msm.basic.remove(molsys, selection='atom_type=="H"')

In [5]:
molsys.topology.chains

  chain_id chain_name chain_type
0        A          A    protein
1        D          A    unknown
2        E          A    unknown

In [6]:
molsys_pdbfixer = msm.build.add_missing_terminal_cappings(molsys, N_terminal='ACE', C_terminal='NME')

In [8]:
molsys = msm.convert(molsys_pdbfixer, 'molsysmt.Topology')

In [10]:
molsys.atoms

      atom_id atom_name atom_type  group_index  component_index  chain_index
0           1         C         C            0                0            0
1           2         O         O            0                0            0
2           3       CH3         C            0                0            0
3           4         N         N            1                0            0
4           5        CA         C            1                0            0
...       ...       ...       ...          ...              ...          ...
1303     1304        C2         C          165                2            0
1304     1305        C3         C          165                2            0
1305     1306        C4         C          165                2            0
1306     1307        C5         C          165                2            0
1307     1308        C6         C          165                2            0

[1308 rows x 6 columns]

In [ ]:
chain_0, chain_1, chain_2 = list(molsys.topology.chains())

In [ ]:
molsys.topology.atoms

In [ ]:
molsys = msm.build.add_missing_hydrogens(molsys, pH=7.4)

In [ ]:
_ = msm.convert(molsys, to_form='t4_lysozyme_L99A.h5msm')