In [1]:
# This cell is removed with the tag: "remove-input"
# As such, it will not be shown in documentation

import warnings
warnings.filterwarnings('ignore')

(Tutorial_Add_missing_heavy_atoms)=
# Add missing heavy atoms

*Adding missing non-hydrogen heavy atoms to a molecular system.*

Some molecular systems—especially those obtained from experimental techniques like X-ray crystallography—may lack certain heavy atoms due to resolution limits or local structural disorder. The function {func}`molsysmt.build.add_missing_heavy_atoms` reconstructs these missing non-hydrogen atoms whenever sufficient topological and geometrical template information is available.

:::{versionadded} 1.0.0
:::

:::{admonition} API documentation
:class: dropdown

Follow this link for a detailed description of the input arguments, raised errors, and returned objects of this function: {func}`molsysmt.build.add_missing_heavy_atoms`.
:::

## Basic usage

Let's show how this function works by building a peptide system and intentionally removing selected heavy atoms to simulate missing structural data:

In [2]:
import molsysmt as msm

In [3]:
molsys = msm.build.build_peptide('AceHisThrNme')

In [4]:
msm.info(molsys)

First, let's remove hydrogen atoms from our system:

In [5]:
molsys = msm.remove(molsys, selection='atom_type=="H"')

In [6]:
msm.build.has_hydrogens(molsys)

False

Next, let's remove specific heavy atoms (`NE2`, `CD2`, `OG1`) to simulate experimental atom loss:

In [7]:
molsys = msm.remove(molsys, selection='atom_name in ["NE2", "CD2", "OG1"]')

We can verify which heavy atoms are detected as missing using {func}`molsysmt.build.get_missing_heavy_atoms`:

In [8]:
msm.build.get_missing_heavy_atoms(molsys)

{1: ['CD2', 'NE2'], 2: ['OG1']}

Now we call {func}`molsysmt.build.add_missing_heavy_atoms` to reconstruct the missing non-hydrogen atoms:

In [9]:
molsys = msm.build.add_missing_heavy_atoms(molsys)

Let's confirm that the missing heavy atoms have been successfully restored:

In [10]:
msm.info(molsys, element='atom')

:::{seealso} Related Tools & References
:class: dropdown

- {ref}`Tutorial_Build_peptide`: Generate capped peptide structures from sequence with {func}`molsysmt.build.build_peptide`.
- {ref}`Tutorial_Info`: Display structural and topological summaries of a molecular system with {func}`molsysmt.basic.info`.
- {ref}`Tutorial_Remove`: Remove atoms from a molecular system with {func}`molsysmt.basic.remove`.
- {ref}`Tutorial_Has_hydrogens`: Check whether a molecular system contains hydrogen atoms with {func}`molsysmt.build.has_hydrogens`.
- {ref}`Tutorial_Get_missing_heavy_atoms`: Identify missing non-hydrogen heavy atoms with {func}`molsysmt.build.get_missing_heavy_atoms`.
- {ref}`Tutorial_Add_missing_heavy_atoms`: Reconstruct missing heavy atoms with {func}`molsysmt.build.add_missing_heavy_atoms`.
- {ref}`Tutorial_Add_missing_hydrogens`: Add missing hydrogen atoms to a molecular system with {func}`molsysmt.build.add_missing_hydrogens`.
:::