In [1]:
# This cell is removed with the tag: "remove-input"
# As such, it will not be shown in documentation

import warnings
warnings.filterwarnings('ignore')

(Tutorial_Add_missing_terminal_cappings)=
# Add missing terminal cappings

*Adding terminal cappings to peptides and proteins.*

Capping the termini of peptides and proteins is often required in molecular modeling to ensure charge neutrality, stability, or to match specific biological conditions. The function {func}`molsysmt.build.add_missing_terminal_cappings` adds chemical capping groups (such as `ACE` for N-terminus and `NME` for C-terminus) or completes uncapped terminal residues.

:::{versionadded} 1.0.0
:::

:::{admonition} API documentation
:class: dropdown

Follow this link for a detailed description of the input arguments, raised errors, and returned objects of this function: {func}`molsysmt.build.add_missing_terminal_cappings`.
:::

## Basic usage

Let's show how this function works using a tripeptide example (`AlaValPro`):

In [2]:
import molsysmt as msm

In [3]:
molsys = msm.build.build_peptide('AlaValPro', to_form='molsysmt.MolSys')

In [4]:
msm.info(molsys, element='group')

As shown, the termini of the peptide are currently incomplete. We now add the atoms required to complete the terminal amino acids without capping groups, producing a charged version of the peptide:

In [5]:
molsys_charged = msm.build.add_missing_terminal_cappings(molsys, N_terminal=None, C_terminal=None)

In [6]:
msm.info(molsys_charged, element='group')

Let's check the group charges under these conditions using {func}`molsysmt.physchem.get_charge`:

In [7]:
msm.physchem.get_charge(molsys_charged, element='group')

To neutralize terminal charges, we can cap the N-terminus with an acetyl group (`ACE`) and the C-terminus with an N-methyl amide group (`NME`):

In [8]:
molsys_uncharged = msm.build.add_missing_terminal_cappings(molsys, N_terminal='ACE', C_terminal='NME')

In [9]:
msm.info(molsys_uncharged, element='group')

We inspect the group charges again to confirm that the capped peptide is now neutral:

In [10]:
msm.physchem.get_charge(molsys_uncharged, element='group')

:::{seealso} Related Tools & References
:class: dropdown

- {ref}`Build peptide <Tutorial_Build_peptide>`: Generate capped peptide structures from sequence with {func}`molsysmt.build.build_peptide`.
- {ref}`Info <Tutorial_Info>`: Display structural and topological summaries of a molecular system with {func}`molsysmt.basic.info`.
- {ref}`Add missing terminal cappings <Tutorial_Add_missing_terminal_cappings>`: Add terminal cappings to peptides or proteins with {func}`molsysmt.build.add_missing_terminal_cappings`.
- {ref}`Get charge <Tutorial_Get_charge>`: Retrieve formal or net electric charges with {func}`molsysmt.physchem.get_charge`.
:::