In [1]:
# This cell is removed with the tag: "remove-input"
# As such, it will not be shown in documentation

import warnings
warnings.filterwarnings('ignore')

(Tutorial_Define_new_chain)=
# Define new chain

*Defining a new chain by grouping a selection of atoms.*

The function {func}`molsysmt.build.define_new_chain` groups any selected set of atoms into a new chain. This is useful when preparing systems for simulation, merging fragments, or reassigning chain identities after structural modifications.

:::{versionadded} 1.0.0
:::

:::{admonition} API documentation
:class: dropdown

Follow this link for a detailed description of the input arguments, raised errors, and returned objects of this function: {func}`molsysmt.build.define_new_chain`.
:::

## Basic usage

Let's show how this function works using a protein system loaded from PDB ID `1TCD`:

In [2]:
import molsysmt as msm

In [3]:
molsys = msm.convert('1TCD')

Let's inspect the current chain composition of the system:

In [4]:
msm.info(molsys, element='chain')

We now assign all water molecules to a new chain labeled `'C'`:

In [5]:
msm.build.define_new_chain(molsys, selection='molecule_type=="water"', chain_name='C')

Let's confirm that the water molecules have been grouped into a new chain:

In [6]:
msm.info(molsys, element='chain')

:::{seealso} Related Tools & References
:class: dropdown

- {ref}`Convert <Tutorial_Convert>`: Convert molecular systems between different forms with {func}`molsysmt.basic.convert`.
- {ref}`Info <Tutorial_Info>`: Display structural and topological summaries of a molecular system with {func}`molsysmt.basic.info`.
- {ref}`Define new chain <Tutorial_Define_new_chain>`: Group a selection of atoms into a new chain with {func}`molsysmt.build.define_new_chain`.
:::