In [1]:
# This cell is removed with the tag: "remove-input"
# As such, it will not be shown in documentation

import warnings
warnings.filterwarnings('ignore')

(Tutorial_Get_missing_heavy_atoms)=
# Get missing heavy atoms

*Identifying missing non-hydrogen heavy atoms in a molecular system.*

Structures solved by experimental methods such as X-ray crystallography often contain missing heavy atoms due to resolution limits or local disorder. The function {func}`molsysmt.build.get_missing_heavy_atoms` analyzes residue topologies against standard templates to identify non-hydrogen heavy atoms that are missing.

:::{versionadded} 1.0.0
:::

:::{admonition} API documentation
:class: dropdown

Follow this link for a detailed description of the input arguments, raised errors, and returned objects of this function: {func}`molsysmt.build.get_missing_heavy_atoms`.
:::

## Basic usage

Let's show how this function works using a protein structure loaded from PDB ID `1BRS`:

In [2]:
import molsysmt as msm

In [3]:
molsys = msm.convert('1BRS', selection='molecule_type=="protein"')

In [4]:
msm.info(molsys, element='molecule')

We now use {func}`molsysmt.build.get_missing_heavy_atoms` to detect missing non-hydrogen atoms across all residues:

In [5]:
missing_heavy_atoms = msm.build.get_missing_heavy_atoms(molsys)

In [6]:
missing_heavy_atoms

{234: ['CD', 'CE', 'CG', 'NZ'],
 237: ['CG', 'OD1', 'OD2'],
 244: ['CD', 'OE1', 'OE2'],
 246: ['CD', 'CG', 'NE2', 'OE1'],
 254: ['CD', 'CE', 'NZ'],
 260: ['CG1', 'CG2'],
 264: ['CD', 'CE', 'CG', 'NZ'],
 282: ['OG'],
 325: ['O'],
 383: ['NE2', 'OE1'],
 385: ['NZ'],
 386: ['CD', 'CG', 'NE2', 'OE1'],
 422: ['CZ', 'NE', 'NH1', 'NH2'],
 429: ['CD', 'CG', 'NE2', 'OE1'],
 465: ['CZ', 'NE', 'NH1', 'NH2'],
 469: ['CD', 'CG', 'NE2', 'OE1'],
 471: ['CD', 'CE', 'CG', 'NZ'],
 472: ['CD', 'CG', 'NE2', 'OE1'],
 473: ['CD1', 'CD2', 'CG'],
 520: ['CD', 'CE', 'NZ'],
 526: ['CD', 'CG', 'OE1', 'OE2'],
 544: ['CD', 'CG', 'OE1', 'OE2'],
 562: ['CD', 'CG', 'OE1', 'OE2'],
 563: ['CG', 'ND2', 'OD1'],
 587: ['O']}

We can identify which molecules contain these missing heavy atoms:

In [7]:
residue_indices = list(missing_heavy_atoms.keys())
molecule_indices = msm.get(molsys, element='molecule', selection='group_index in @residue_indices', molecule_index=True)

In [8]:
msm.info(molsys, element='molecule', selection='molecule_index in @molecule_indices')

Finally, let's check if the system has hydrogen atoms using {func}`molsysmt.build.has_hydrogens`:

In [9]:
msm.build.has_hydrogens(molsys)

False

:::{seealso} Related Tools & References
:class: dropdown

- {ref}`Convert <Tutorial_Convert>`: Convert molecular systems between different forms with {func}`molsysmt.basic.convert`.
- {ref}`Info <Tutorial_Info>`: Display structural and topological summaries of a molecular system with {func}`molsysmt.basic.info`.
- {ref}`Get missing heavy atoms <Tutorial_Get_missing_heavy_atoms>`: Identify missing non-hydrogen heavy atoms with {func}`molsysmt.build.get_missing_heavy_atoms`.
- {ref}`Get <Tutorial_Get>`: Retrieve attribute values from a molecular system with {func}`molsysmt.basic.get`.
- {ref}`Has hydrogens <Tutorial_Has_hydrogens>`: Check whether a molecular system contains hydrogen atoms with {func}`molsysmt.build.has_hydrogens`.
- {ref}`Add missing heavy atoms <Tutorial_Add_missing_heavy_atoms>`: Reconstruct missing non-hydrogen heavy atoms with {func}`molsysmt.build.add_missing_heavy_atoms`.
:::