In [1]:
# This cell is removed with the tag: "remove-input"
# As such, it will not be shown in documentation

import warnings
warnings.filterwarnings('ignore')

(Tutorial_Solvate)=
# Solvate

*Adding solvent molecules and ions to solvate a molecular system.*

The function {func}`molsysmt.build.solvate` embeds a molecular system in a periodic solvent box (such as cubic or truncated octahedral geometries) and optionally adds neutralizing counterions.

:::{versionadded} 1.0.0
:::

:::{admonition} API documentation
:class: dropdown

Follow this link for a detailed description of the input arguments, raised errors, and returned objects of this function: {func}`molsysmt.build.solvate`.
:::

## Basic usage

Let's show how to solvate a protein structure loaded from PDB ID `1VII`:

In [2]:
import molsysmt as msm

In [3]:
molsys = msm.convert('pdb_id:1vii', to_form='molsysmt.MolSys')

In [4]:
msm.info(molsys)

We check whether the initial system is solvated using {func}`molsysmt.build.is_solvated`:

In [5]:
msm.build.is_solvated(molsys)

False

Now we solvate the system in a cubic box with 14 Å clearance using {func}`molsysmt.build.solvate`:

In [6]:
molsys_cub = msm.build.solvate(molsys, box_shape='cubic', clearance='14.0 angstroms')

In [7]:
msm.build.is_solvated(molsys_cub)

True

In [8]:
msm.info(molsys_cub)

We inspect the box vectors and angles of the solvated system using {func}`molsysmt.basic.get`:

In [9]:
box, box_angles, box_shape = msm.get(molsys_cub, element='system', box=True, box_angles=True, box_shape=True)

In [10]:
print('Box:', box)
print('Angles:', box_angles)
print('Shape:', box_shape)

Box: [[[4.930948498633192 0.0 0.0]  [0.0 4.930948498633192 0.0]  [0.0 0.0 4.930948498633192]]] nanometer
Angles: [[1.570796 1.570796 1.570796]] radian
Shape: cubic

We can wrap the protein to PBC boundaries and visualize the solvated system using {func}`molsysmt.basic.view`:

In [11]:
molsys_cub = msm.pbc.wrap_to_pbc(molsys_cub, center_of_selection='molecule_type=="peptide"')

In [12]:
molsysviewer_htmlfile = '_static/views/tools_build_solvate_1.html'

In [13]:
msm.view(molsys_cub)

'<iframe src="../../../../_static/views/tools_build_solvate_1.html" width="100%" height="480px"\n        style="border:none;"></iframe>'

## Periodic box geometries

Alternative periodic box geometries (such as truncated octahedral) allow efficient solvation with fewer solvent molecules:

In [14]:
molsys_oct = msm.build.solvate(molsys, box_shape='truncated octahedral', clearance='14.0 angstroms')

In [15]:
msm.info(molsys_oct)

In [16]:
molsys_oct = msm.pbc.wrap_to_pbc(molsys_oct, center_of_selection='molecule_type=="peptide"')

In [17]:
molsysviewer_htmlfile = '_static/views/tools_build_solvate_2.html'

In [18]:
msm.view(molsys_oct)

'<iframe src="../../../../_static/views/tools_build_solvate_2.html" width="100%" height="480px"\n        style="border:none;"></iframe>'

:::{seealso} Related Tools & References
:class: dropdown

- {ref}`Convert <Tutorial_Convert>`: Convert molecular systems between different forms with {func}`molsysmt.basic.convert`.
- {ref}`Info <Tutorial_Info>`: Display structural and topological summaries of a molecular system with {func}`molsysmt.basic.info`.
- {ref}`Is solvated <Tutorial_Is_solvated>`: Check whether a molecular system contains solvent molecules with {func}`molsysmt.build.is_solvated`.
- {ref}`Solvate <Tutorial_Solvate>`: Add solvent molecules around a molecular system with {func}`molsysmt.build.solvate`.
- {ref}`Get <Tutorial_Get>`: Retrieve attribute values from a molecular system with {func}`molsysmt.basic.get`.
- {ref}`Wrap to PBC <Tutorial_Wrap_to_pbc>`: Wrap atom coordinates into periodic box boundaries with {func}`molsysmt.pbc.wrap_to_pbc`.
- {ref}`View <Tutorial_View>`: Visualize a molecular system with {func}`molsysmt.basic.view`.
:::