In [1]:
# This cell is removed with the tag: "remove-input"
# As such, it will not be shown in documentation

import warnings
warnings.filterwarnings('ignore')

(Tutorial_Add)=
# Add

*Adding elements of a molecular system into another molecular system.*

Elements coming from different molecular systems can be added to a given system with the {func}`molsysmt.basic.add` function.

:::{versionadded} 1.0.0
:::

## How this function works

```{admonition} API documentation
Follow this link for a detailed description of the input arguments, raised errors, and returned objects of this function: {func}`molsysmt.basic.add`.
```

Let's show how this function works with three peptides defined as three different molecular systems: proline dipeptide ($A$), valine dipeptide ($B$), and lysine dipeptide ($C$).

In [2]:
import molsysmt as msm

In [3]:
molsys_A = msm.build.build_peptide('AceProNme')
molsys_B = msm.build.build_peptide('AceValNme')
molsys_C = msm.build.build_peptide('AceLysNme')

## Basic usage

The molecular systems $B$ and $C$ need to be translated to avoid spatial overlap once their elements are added to $A$ (since all systems are built centered around the origin).

In [4]:
molsys_B = msm.structure.translate(molsys_B, translation='[-1.0, 0.0, 0.0] nanometers')
molsys_C = msm.structure.translate(molsys_C, translation='[1.0, 0.0, 0.0] nanometers')

Let's inspect how $A$ is defined before adding $B$ and $C$:

In [5]:
msm.info(molsys_A)

Now let's add the elements of $B$ and $C$ into $A$:

In [6]:
msm.add(molsys_A, molsys_B)
msm.add(molsys_A, molsys_C)

:::{tip}
All methods defined in the {ref}`molsysmt.basic <API basic>` module can be invoked also from the main level of the library. Hence, {func}`molsysmt.add` is the same method as {func}`molsysmt.basic.add`.
:::

After the addition, we inspect $A$ again. Notice the larger count of atoms, groups, and molecules:

In [7]:
msm.info(molsys_A, element='system')

We can also visualize the combined system interactively. Try rotating and zooming to observe the spatial separation between $A$, $B$, and $C$.

In [8]:
# This cell is removed with the tag: "remove-input"
# As such, it will not be shown in documentation

molsysviewer_htmlfile = '_static/views/tools_basic_add.html'

In [9]:
msm.view(molsys_A, standard=True)

'<iframe src="../../../../../../../../../_static/views/tools_basic_add.html" width="100%" height="480px"\n        style="border:none;"></iframe>'

## Creating a new system (`in_place=False`)

By default, `msm.add` modifies the target system in place. If you prefer not to modify the original system, pass `in_place=False` to return a new molecular system containing the combined elements:

In [10]:
molsys_D = msm.add(molsys_B, molsys_C, in_place=False)

In [11]:
msm.get(molsys_B, n_peptides=True)

1

In [12]:
msm.get(molsys_C, n_peptides=True)

1

In [13]:
msm.get(molsys_D, n_peptides=True)

2

## Adding selected elements (`selection`)

Instead of adding all elements from the source system, you can restrict the addition to a specific selection of atoms or residues using `selection`. For example, let's add only the Lysine residue from $C$ into $B$:

In [14]:
molsys_E = msm.add(molsys_B, molsys_C, selection='group_name=="LYS"', in_place=False)

In [15]:
msm.info(molsys_E)

## Specifying structure indices (`structure_indices`)

When adding elements from a multi-structure source system into a target system with fewer structures, pass `structure_indices` to select which frame's coordinates to add:

In [16]:
molsys_A1 = msm.build.build_peptide('AceProNme')
molsys_A2 = msm.structure.translate(molsys_A1, translation='[0.1, 0.1, 0.1] nanometers')
molsys_multi = msm.concatenate_structures([molsys_A1, molsys_A2])
molsys_F = msm.add(molsys_B, molsys_multi, structure_indices=0, in_place=False)

In [17]:
msm.info(molsys_F)

:::{seealso}
{ref}`Tutorial_Build_peptide`:    
Build natural peptides with or without terminal caps.

{ref}`Tutorial_Translate`:    
Translate entire molecular systems or specific selections in space.

{ref}`Tutorial_Info`:    
Display a summary of the contents, topology, and structural data of a molecular system.

{ref}`Tutorial_View`:    
Visualize a molecular system.

{ref}`Tutorial_Get`:    
Retrieve attribute values from a molecular system.

{ref}`Tutorial_Select`:  
Select elements from a molecular system to work with subsets of atoms, groups, or molecules.

{ref}`Tutorial_Merge`:    
Combine multiple molecular systems by merging their elements into a new system.
:::