In [1]:
# This cell is removed with the tag: "remove-input"
# As such, it will not be shown in documentation

import warnings
warnings.filterwarnings('ignore')

(Tutorial_Copy)=
# Copy

*Creating independent copies of molecular systems.*

The function {func}`molsysmt.basic.copy` allows you to create a fully independent copy of a molecular system.

:::{versionadded} 1.0.0
:::

:::{admonition} API documentation
:class: dropdown

Follow this link for a detailed description of the input arguments, raised errors, and returned objects of this function: {func}`molsysmt.basic.copy`.
:::

## Basic usage

Let's show how this function works using a PDB structure (`181L`):

In [2]:
import molsysmt as msm

In [3]:
molsys = msm.convert('181L', to_form='molsysmt.MolSys')

In [4]:
msm.info(molsys)

In [5]:
molsys_copy = msm.copy(molsys)

:::{tip}
:class: dropdown

All methods defined in the {ref}`molsysmt.basic <API basic>` module can also be invoked from the main level of the library. Hence, {func}`molsysmt.copy` is the same function as {func}`molsysmt.basic.copy`.
:::

Although the original and copied systems are structurally identical, they are stored as distinct Python objects:

In [6]:
id(molsys)!= id(molsys_copy)

True

But they represent the same molecular system:

In [7]:
msm.compare(molsys, molsys_copy, rule='equal')

True

In [8]:
msm.info(molsys_copy)

:::{seealso} Related Tools & References
:class: dropdown

- {ref}`Tutorial_Convert`: Convert a molecular system into another form or forms with {func}`molsysmt.basic.convert`.
- {ref}`Tutorial_Info`: Print a summary of the contents, topology, and structural data of a molecular system with {func}`molsysmt.basic.info`.
- {ref}`Tutorial_Compare`: Compare molecular systems across selected attributes with {func}`molsysmt.basic.compare`.
:::