In [1]:
# This cell is removed with the tag: "remove-input"
# As such, it will not be shown in documentation

import warnings
warnings.filterwarnings('ignore')

(Tutorial_Info)=
# Info

*Displaying summary information about a molecular system and its elements.*

MolSysMT provides a function to display a concise summary of a molecular system and its elements: {func}`molsysmt.basic.info`. This function works at different levels depending on the selected element type — `atom`, `group`, `component`, `molecule`, `chain`, `entity`, or `system`. The output is a `pandas.DataFrame`.

:::{hint}
:class: dropdown

Visit the section {ref}`Introduction_Elements` for a detailed overview of element hierarchy in MolSysMT.
:::

:::{versionadded} 1.0.0
:::

:::{admonition} API documentation
:class: dropdown

Follow this link for a detailed description of the input arguments, raised errors, and returned objects of this function: {func}`molsysmt.basic.info`.
:::

## Basic usage

Let's show how this function works using a PDB structure (`181L`):

In [2]:
import molsysmt as msm

In [3]:
molsys = msm.convert('181L')

By default, {func}`molsysmt.basic.info` supplies a summary of the system as a Pandas dataframe:

In [4]:
msm.info(molsys)

:::{tip}
:class: dropdown

All methods defined in the {ref}`molsysmt.basic <API basic>` module can also be invoked from the main level of the library. Hence, {func}`molsysmt.info` is the same function as {func}`molsysmt.basic.info`.
:::

But summary information on other elements such as atoms, groups, components, molecules, chains or entities can be obtained.

## With atoms

Example of how the function works at the `atom` level:

In [5]:
msm.info(molsys, element='atom', selection='molecule_type=="ion"')

## With groups

Example of how the function works at the `group` level:

In [6]:
msm.info(molsys, element='group', selection=[9,10,11,12])

## With components

The function can also be applied to the component level, as shown below:

In [7]:
msm.info(molsys, element='component', selection='molecule_type=="small molecule"')

## With molecules

Let's see an example of how this function works with molecules:

In [8]:
msm.info(molsys, element='molecule',
         selection='molecule_type!=["water", "protein"] within 4.0 angstroms of molecule_type=="protein"')

## With chains

The function can also be applied to `chain` elements as shown below:

In [9]:
msm.info(molsys, element='chain', selection='molecule_type=="water"')

## With entities

This example shows how to obtain a summary of `entity` elements:

In [10]:
msm.info(molsys, element='entity')

## With system

Let's see an example of how this function works with the system (default option):

In [11]:
msm.info(molsys)

:::{seealso} Related Tools & References
:class: dropdown

- {ref}`Introduction_Elements`: Describe the different hierarchical levels (atom, group, component, molecule, chain, entity, system) used in molecular systems.
- {ref}`Tutorial_Convert`: Convert a molecular system into another form or forms with {func}`molsysmt.basic.convert`.
- {ref}`Tutorial_Info`: Display summary information about a molecular system and its elements with {func}`molsysmt.basic.info`.
- {ref}`Tutorial_Get_label`: Generate formatted labels for elements in a molecular system with {func}`molsysmt.basic.get_label`.
:::