In [1]:
# This cell is removed with the tag: "remove-input"
# As such, it will not be shown in documentation

import warnings
warnings.filterwarnings('ignore')

(Tutorial_Remove)=
# Remove

*Removing atoms or structures from a molecular system.*

The function {func}`molsysmt.basic.remove` allows removing atoms or structures from a molecular system.

:::{versionadded} 1.0.0
:::

:::{admonition} API documentation
:class: dropdown

Follow this link for a detailed description of the input arguments, raised errors, and returned objects of this function: {func}`molsysmt.basic.remove`.
:::

## Basic usage

Let's show how this function works with a PDB structure (`181L`). The input argument `selection` allows us to define the elements to be removed:

In [2]:
import molsysmt as msm

In [3]:
molsys = msm.convert('181L')

In [4]:
msm.info(molsys, element='chain')

In [5]:
molsys_trimmed = msm.remove(molsys, selection='chain_index==[1,2,3,4,5]')

:::{tip}
:class: dropdown

All methods defined in the {ref}`molsysmt.basic <API basic>` module can also be invoked from the main level of the library. Hence, {func}`molsysmt.remove` is the same function as {func}`molsysmt.basic.remove`.
:::

In [6]:
msm.info(molsys_trimmed, element='chain')

## Removing structures

The function {func}`molsysmt.basic.remove` can also remove structures from a molecular system. The input argument `structure_indices` specifies the structures to be removed:

In [7]:
pdbfile = msm.systems['Trp-Cage']['1l2y.pdb']
molsys = msm.convert(pdbfile, to_form='molsysmt.Structures')

:::{note} Demo Systems Catalog
:class: dropdown

This tutorial uses demonstration datasets provided by MolSysMT. To explore the full catalog of bundled systems, forms, and file paths, visit the {ref}`Demo Systems <user-foundations-entrance-demo-systems>` guide.
:::

In [8]:
msm.info(molsys)

In [9]:
molsys_trimmed = msm.remove(molsys, structure_indices=range(1,38))

In [10]:
msm.info(molsys_trimmed)

:::{seealso} Related Tools & References
:class: dropdown

- {ref}`user-foundations-entrance-demo-systems`: Explore demonstration datasets used for testing and tutorials.
- {ref}`Tutorial_Convert`: Convert a molecular system into another form with {func}`molsysmt.basic.convert`.
- {ref}`Tutorial_Info`: Display a summary of the contents of a molecular system with {func}`molsysmt.basic.info`.
- {ref}`Tutorial_Remove`: Remove atoms or structures from a molecular system with {func}`molsysmt.basic.remove`.
- {ref}`Tutorial_Select`: Select atoms or structural elements using flexible selection syntax with {func}`molsysmt.basic.select`.
:::